import type { Metadata } from "next";
import {  Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Footer from "./components/layouts/footer";
import NavSection from "./components/layouts/nav-section";

const inter = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shankham",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
        suppressHydrationWarning
      >
        <NavSection />
        {children}
        <Footer />
      </body>
    </html>
  );
}
